### ISSUE TITLE
使用cqhttp时候提示注册QQ实例时出现错误

### ISSUE THREAD

**Issue by 1825679767** [fuqiuluo/unidbg-fetch-qsign#144]
[2023-07-19 07:58:45] [WARNING]: 注册QQ实例时出现错误: Get "http://127.0.0.1:8089/register?uin=211800445&android_id=33306162663339653162316164386566&guid=b37c1007b18f8d02ab8ab03922d4694c&qimei36=5219be532708bf91b6b6f933100012b1730c&key=114514": context deadline exceeded (Client.Timeout exceeded while awaiting headers) server: http://127.0.0.1:8089/
key和端口都检查过了，启动都是用的8.9.63

**Comment by fuqiuluo** [comment]
超时了，发一下qign日志看看

**Comment by qn8524king** [comment]
> 超时了，发一下qign日志看看

付一下我的吧

[root@VM-8-12-centos ~]# docker logs qsign -f
Using base path /srv/qsign/qsign/txlib/8.9.63
02:43:28.700 [main] INFO ktor.application - Autoreload is disabled because the development mode is off.
02:43:29.316 [main] INFO ktor.application - Application started in 0.688 seconds.
02:43:29.324 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
02:43:29.352 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
02:43:29.352 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 11
02:43:29.354 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
02:43:29.355 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
02:43:29.355 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.storeFence: available
02:43:29.356 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
02:43:29.356 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: unavailable: Reflective setAccessible(true) disabled
02:43:29.357 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
02:43:29.358 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable: class io.netty.util.internal.PlatformDependent0$7 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @782a4fff
02:43:29.359 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
02:43:29.359 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
02:43:29.381 [main] DEBUG io.netty.util.internal.PlatformDependent - maxDirectMemory: 524288000 bytes (maybe)
02:43:29.381 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
02:43:29.382 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
02:43:29.384 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
02:43:29.384 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
02:43:29.385 [main] DEBUG io.netty.util.internal.CleanerJava9 - java.nio.ByteBuffer.cleaner(): available
02:43:29.385 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
02:43:29.396 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)
02:43:29.397 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.deleteLibAfterLoading: true
02:43:29.397 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.tryPatchShadedId: true
02:43:29.397 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.detectNativeLibraryDuplicates: true
02:43:29.414 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 4
02:43:29.425 [main] DEBUG io.netty.util.concurrent.GlobalEventExecutor - -Dio.netty.globalEventExecutor.quietPeriodSeconds: 1
02:43:29.431 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
02:43:29.431 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
02:43:29.437 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
02:43:29.437 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
02:43:29.445 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
02:43:29.476 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 8 (auto-detected)
02:43:29.480 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
02:43:29.480 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
02:43:29.483 [main] DEBUG io.netty.util.NetUtilInitializations - Loopback interface: lo (lo, 127.0.0.1)
02:43:29.484 [main] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 128
02:43:29.485 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 02:42:ac:ff:fe:11:00:03 (auto-detected)
02:43:29.497 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
02:43:29.497 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
02:43:29.524 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 4
02:43:29.524 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 4
02:43:29.524 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
02:43:29.524 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 9
02:43:29.524 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 4194304
02:43:29.524 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
02:43:29.525 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
02:43:29.525 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
02:43:29.525 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
02:43:29.525 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
02:43:29.525 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: false
02:43:29.525 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
02:43:29.536 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
02:43:29.536 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
02:43:29.536 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
02:43:29.563 [DefaultDispatcher-worker-1] INFO ktor.application - Responding at http://0.0.0.0:8080
02:43:36.185 [eventLoopGroupProxy-3-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
02:43:36.185 [eventLoopGroupProxy-3-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
02:43:36.186 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@3cd0cbce
02:43:36.246 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
02:43:36.246 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
02:43:36.246 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.chunkSize: 32
02:43:36.246 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.blocking: false
02:43:36.246 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.batchFastThreadLocalOnly: true
02:43:36.372 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.NativeLibraryUtil - processor is INTEL_64 os.arch is amd64
02:43:36.372 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_64 os.name is linux
02:43:36.372 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_64 os.name is linux
02:43:36.372 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is natives/linux_64/
02:43:36.372 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is libunicorn.so
02:43:36.374 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - URL is jar:file:/srv/qsign/qsign/lib/unidbg-fix.jar!/natives/linux_64/libunicorn.so
02:43:36.374 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - URL path is file:/srv/qsign/qsign/lib/unidbg-fix.jar!/natives/linux_64/libunicorn.so
02:43:36.375 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - Extracting 'jar:file:/srv/qsign/qsign/lib/unidbg-fix.jar!/natives/linux_64/libunicorn.so' to '/tmp/nativelib-loader_8908391489213936257/libunicorn.so'
[FEKit_]info: device_token_entry.h:87 initUin 647172130
[FEKit_]info: device_info.h:583 start create xwid
Jul 19, 2023 2:43:38 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/999
Jul 19, 2023 2:43:38 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/128
Jul 19, 2023 2:43:38 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/10
Jul 19, 2023 2:43:38 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/11
Jul 19, 2023 2:43:38 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/12
Jul 19, 2023 2:43:38 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/13
Jul 19, 2023 2:43:38 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/14
Jul 19, 2023 2:43:38 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/15
Jul 19, 2023 2:43:38 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/16
Jul 19, 2023 2:43:38 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/17
Jul 19, 2023 2:43:38 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/18
Jul 19, 2023 2:43:38 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/19
Jul 19, 2023 2:43:38 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/20
Jul 19, 2023 2:43:39 AM com.github.unidbg.linux.ARM64SyscallHandler openat
INFO: openat dirfd=-100, pathname=/data/user/0/com.tencent.mobileqq/files/.system_android_l2, oflags=0x42, mode=1b0
Jul 19, 2023 2:43:39 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/system/lib/libhoudini.so
Jul 19, 2023 2:43:39 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/system/lib64/libhoudini.so
[FEKit_]info: device_info.h:610 create xwid complete
[FEKit_]info: device_info.h:620 start create xwid step2
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/999
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/128
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/10
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/11
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/12
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/13
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/14
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/15
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/16
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/17
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/18
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/19
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/data/user/20
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler openat
INFO: openat dirfd=-100, pathname=/data/user/0/com.tencent.mobileqq/files/.system_android_l2, oflags=0x42, mode=1b0
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/system/lib/libhoudini.so
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler stat64
INFO: stat64 pathname=/system/lib64/libhoudini.so
[FEKit_]info: device_info.h:629 create xwid step2 complete ret is 71
[FEKit_]info: device_token.h:89 create new xwId complete
Jul 19, 2023 2:43:45 AM moe.fuqiuluo.unidbg.env.FileResolver resolve
WARNING: Couldn't find file: /data/app/~~vbcRLwPxS0GyVfqT-nCYrQ==/com.tencent.mobileqq-xJKJPVp9lorkCgR_w5zhyA==/base.apk
Jul 19, 2023 2:43:45 AM com.github.unidbg.linux.ARM64SyscallHandler openat
INFO: openat dirfd=-100, pathname=/data/app/~~vbcRLwPxS0GyVfqT-nCYrQ==/com.tencent.mobileqq-xJKJPVp9lorkCgR_w5zhyA==/base.apk, oflags=0x0, mode=0
[FEKit_]error: o3_channel_encrypt.h:275 gen new channel
FEBound.transform(2884da996370d46f56e2b1efa689ed51649db1901f9f5d7667544ec36dd45dfd) => 0429e5c017d5c7760e6e563f6aa0519ea79100c5733a86dcaa1704874412b164
[FEKit_]error: o3_channel_encrypt.h:491 est check: a9deb9623a2c3d4f08a4ba1949cef4cdc6543b1cf03c470a229ce5ac5017ba237ca5b7ffcfd4247e346e2d6d671590f5
[FEKit_]error: ChannelManager.cpp:72 o3cm@S: GetSecConf, trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
uin = 647172130, id = 0, sendPacket(cmd = trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish, data = 0a0a476574536563436f6e66122102838f0cc4564ce0ca1caf011a79543d7e984d77318ab39abb451d8a37a04b4a0e22423833633536323337366539323963626161353837383730666262373264386337663363666539373731646631343830386562333061613931373932336664643563652a48a4c4cdcef5a7b3c7c72be7a685f06d0fc9c7762b0ff27b95c634bf9709ee9f222e5d4754f695839a80af1ac80579fb734c1c60c469b42f2ed74b0c4b6421b6a160172ddf8b1398133220213631072a0d1c193fee6aee428a33814c7be838758a030d92edd099e15542ab3a30a9deb9623a2c3d4f08a4ba1949cef4cdc6543b1cf03c470a229ce5ac5017ba237ca5b7ffcfd4247e346e2d6d671590f5)

到这里时gocq已经超时了

**Comment by jkjoy** [comment]
[2023-07-19 17:15:46] [WARNING]: 获取T544 sign时出现错误: encoding/hex: invalid byte: U+0069 'i'

**Comment by fuqiuluo** [comment]
> [2023-07-19 17:15:46] [WARNING]: 获取T544 sign时出现错误: encoding/hex: invalid byte: U+0069 'i'

这个是gocq没适配最新版的qsign导致的，如果想不更换gocq的话，那就更换qsign到1.1.0版本。否则请使用gocq-dev
